services:
  
  ########## POSTGRES ##########
  
  db:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 5


  ########## REDIS ##########

  redis_db:
    image: redis
    restart: always
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis_data:/data
    command: >
      redis-server
      /etc/redis/redis.conf
      --requirepass ${REDIS_PASSWORD}
      --appendonly yes
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5

  ########## VOLUMES ##########
volumes:
  redis_data:

  

