env: "dev"
storage_path: "storage/storage.db"
# dummy db connection string (local postgres)
db_conn: "postgresql://postgres:123@localhost:5432/go_blog?sslmode=disable"
redis_conn: "redis://<user>:<pass>@localhost:6379/<db>"
jwt_secret: "your_jwt_secret_key_kojjdkfhjkdgfjhsgjhgdrgr"
http_server:
  host: "localhost"
  port: 3000